name = "pws_worker"
main = "pws_worker/build/index.js"
compatibility_date = "2025-12-27"

kv_namespaces = [
  { binding = "user" },
  { binding = "save" }
]

[build]
command = "worker-build --release"
cwd = "./pws_worker"

[observability]
enabled = true

[vars]
LOG_LEVEL="DEBUG"